name: dailyschedule

on:
  schedule:
    - cron: '0 1,10,12,19 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run update sheets
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        run: python update_sheets.py
