name: install-packages
on: [push]
jobs:
  install-requirements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install requests
